"""add cities and rival_relationships tables

Revision ID: 316dace21802
Revises: cb99d2b5d674
Create Date: 2026-09-17 18:08:59.484768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316dace21802'
down_revision: Union[str, Sequence[str], None] = 'cb99d2b5d674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('founded_month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_session_id'), ['session_id'], unique=False)

    op.create_table('rival_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('rival_a', sa.String(), nullable=False),
    sa.Column('rival_b', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rival_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rival_relationships_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rival_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rival_relationships_session_id'))

    op.drop_table('rival_relationships')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_session_id'))

    op.drop_table('cities')
    # ### end Alembic commands ###
