"""add trade routes table

Revision ID: 6a3bae5e4a54
Revises: c894ab83505c
Create Date: 2026-09-22 19:48:52.934819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3bae5e4a54'
down_revision: Union[str, Sequence[str], None] = 'c894ab83505c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('rival_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'rival_id', name='uq_trade_route_session_rival')
    )
    with op.batch_alter_table('trade_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_routes_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_routes_session_id'))

    op.drop_table('trade_routes')
    # ### end Alembic commands ###
