"""add personality to rivals and owner to cities

Revision ID: 6fd7f24bd0c6
Revises: 80440b91c4b9
Create Date: 2026-09-22 10:41:22.562296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd7f24bd0c6'
down_revision: Union[str, Sequence[str], None] = '80440b91c4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), server_default='player', nullable=False))

    with op.batch_alter_table('rival_nations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personality', sa.String(), server_default='economic', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rival_nations', schema=None) as batch_op:
        batch_op.drop_column('personality')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
