"""add game_logs table

Revision ID: 80440b91c4b9
Revises: 316dace21802
Create Date: 2026-09-22 09:52:15.450950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80440b91c4b9'
down_revision: Union[str, Sequence[str], None] = '316dace21802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_logs_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_logs_session_id'))

    op.drop_table('game_logs')
    # ### end Alembic commands ###
