"""add buildings and wonders

Revision ID: c894ab83505c
Revises: cbfbefeb6a33
Create Date: 2026-09-22 14:59:58.632014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c894ab83505c'
down_revision: Union[str, Sequence[str], None] = 'cbfbefeb6a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wonder_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('wonder_id', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'wonder_id', name='uq_wonder_claim_session_wonder')
    )
    with op.batch_alter_table('wonder_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wonder_claims_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('nations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('built_buildings', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('current_building', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('current_building_months_left', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('current_wonder', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('current_wonder_months_left', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nations', schema=None) as batch_op:
        batch_op.drop_column('current_wonder_months_left')
        batch_op.drop_column('current_wonder')
        batch_op.drop_column('current_building_months_left')
        batch_op.drop_column('current_building')
        batch_op.drop_column('built_buildings')

    with op.batch_alter_table('wonder_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wonder_claims_session_id'))

    op.drop_table('wonder_claims')
    # ### end Alembic commands ###
