"""add war_months to rival_nations

Revision ID: cb99d2b5d674
Revises: cdd09a3eb82c
Create Date: 2026-09-17 17:30:35.941648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb99d2b5d674'
down_revision: Union[str, Sequence[str], None] = 'cdd09a3eb82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rival_nations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('war_months', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rival_nations', schema=None) as batch_op:
        batch_op.drop_column('war_months')

    # ### end Alembic commands ###
