"""add national_trait to nations and rival_nations

Revision ID: cbfbefeb6a33
Revises: 6fd7f24bd0c6
Create Date: 2026-09-22 14:39:36.332874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfbefeb6a33'
down_revision: Union[str, Sequence[str], None] = '6fd7f24bd0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_trait', sa.String(), server_default='military', nullable=False))

    with op.batch_alter_table('rival_nations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_trait', sa.String(), server_default='military', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rival_nations', schema=None) as batch_op:
        batch_op.drop_column('national_trait')

    with op.batch_alter_table('nations', schema=None) as batch_op:
        batch_op.drop_column('national_trait')

    # ### end Alembic commands ###
