"""baseline: existing schema

Revision ID: cdd09a3eb82c
Revises: 
Create Date: 2026-09-17 17:15:14.462913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd09a3eb82c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owned_tiles', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'player'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owned_tiles', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'player'"))

    # ### end Alembic commands ###
