"""add nation difficulty

Revision ID: f615b4c87956
Revises: 6a3bae5e4a54
Create Date: 2026-09-23 10:50:59.068677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f615b4c87956'
down_revision: Union[str, Sequence[str], None] = '6a3bae5e4a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(), server_default='normal', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nations', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
